const bartanInventory = [
  {
    name: "Bartan Holder",
    hindiName: "बर्तन होल्डर",
    requirementType: "BARTAN",
    image: "BartanHolder.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Bartan Stand",
    hindiName: "बर्तन स्टैंड",
    requirementType: "BARTAN",
    image: "BartanStand.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Belan",
    hindiName: "बेलन",
    requirementType: "BARTAN",
    image: "Belan.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Belcha",
    hindiName: "बेलचा",
    requirementType: "BARTAN",
    image: "Belcha.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Bowl",
    hindiName: "कटोरा",
    requirementType: "BARTAN",
    image: "Bowl.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Catle Dhakan",
    hindiName: "कैटल ढक्कन",
    requirementType: "BARTAN",
    image: "CatleDhakan.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Chakla",
    hindiName: "चकला",
    requirementType: "BARTAN",
    image: "Chakla.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Chamcha",
    hindiName: "चमचा",
    requirementType: "BARTAN",
    image: "Chamcha.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Chanota",
    hindiName: "छनौटा",
    requirementType: "BARTAN",
    image: "Chanota.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Chanota Big",
    hindiName: "बड़ा छनौटा",
    requirementType: "BARTAN",
    image: "ChanotaBig.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Chawal Bharne Wala",
    hindiName: "चावल भरने वाला",
    requirementType: "BARTAN",
    image: "ChawalBharneWala.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Cholni",
    hindiName: "छलनी",
    requirementType: "BARTAN",
    image: "Cholni.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "DABBH",
    hindiName: "डब्बा",
    requirementType: "BARTAN",
    image: "DABBH.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Fiber Plate",
    hindiName: "फाइबर प्लेट",
    requirementType: "BARTAN",
    image: "FiberPlate.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Ken Big",
    hindiName: "बड़ा केन",
    requirementType: "BARTAN",
    image: "KenBig.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Ken Big Dhakkan",
    hindiName: "बड़े केन का ढक्कन",
    requirementType: "BARTAN",
    image: "KenBigDhakkan.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Ken Small",
    hindiName: "छोटा केन",
    requirementType: "BARTAN",
    image: "KenSmall.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Ken Small (Andhara)",
    hindiName: "छोटा केन (अंधारा)",
    requirementType: "BARTAN",
    image: "KenSmallAndhara.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Ken Small Dhakkan",
    hindiName: "छोटे केन का ढक्कन",
    requirementType: "BARTAN",
    image: "KenSmallDhakkan.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Ken with Dhakkan",
    hindiName: "ढक्कन वाला केन",
    requirementType: "BARTAN",
    image: "KenWithDhakkan.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Lunch Box",
    hindiName: "लंच बॉक्स",
    requirementType: "BARTAN",
    image: "LunchBox.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Patila",
    hindiName: "पतीला",
    requirementType: "BARTAN",
    image: "Patila.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Patila Small",
    hindiName: "छोटा पतीला",
    requirementType: "BARTAN",
    image: "PatilaSmall.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Patila Top Big",
    hindiName: "बड़ा पतीला टॉप",
    requirementType: "BARTAN",
    image: "PatilaTopBig.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Patila Top Big Dhakkan",
    hindiName: "बड़े पतीला टॉप का ढक्कन",
    requirementType: "BARTAN",
    image: "PatilaTopBigDhakkan.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Small Bharni",
    hindiName: "छोटी भरनी",
    requirementType: "BARTAN",
    image: "SmallBharni.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Small Chamcha",
    hindiName: "छोटा चमचा",
    requirementType: "BARTAN",
    image: "SmallChamcha.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Small Chonota",
    hindiName: "छोटा छनौटा",
    requirementType: "BARTAN",
    image: "SmallChonota.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Small Patila with Dhakan",
    hindiName: "ढक्कन वाला छोटा पतीला",
    requirementType: "BARTAN",
    image: "SmallPatilaWithDhakan.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Spoon",
    hindiName: "चम्मच",
    requirementType: "BARTAN",
    image: "Spoon.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "SS BELCHA",
    hindiName: "स्टेनलेस स्टील बेलचा",
    requirementType: "BARTAN",
    image: "SSBelcha.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "SS Dabhuk",
    hindiName: "स्टेनलेस स्टील डाभुक",
    requirementType: "BARTAN",
    image: "SSDabhuk.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "S.S. Ken Handle",
    hindiName: "स्टेनलेस स्टील केन हैंडल",
    requirementType: "BARTAN",
    image: "SSKenHandle.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "SS Milk Jug 5lt.",
    hindiName: "स्टेनलेस स्टील मिल्क जग 5 लीटर",
    requirementType: "BARTAN",
    image: "SSMilkJug5lt.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "SS MUG 5KG",
    hindiName: "स्टेनलेस स्टील मग 5 किलो",
    requirementType: "BARTAN",
    image: "SSMug5KG.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "SS Palta",
    hindiName: "स्टेनलेस स्टील पलटा",
    requirementType: "BARTAN",
    image: "SSPalta.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Bharni Big",
    hindiName: "बड़ी भरनी",
    requirementType: "BARTAN",
    image: "BharniBig.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Bharni Big Dhakkan",
    hindiName: "बड़ी भरनी का ढक्कन",
    requirementType: "BARTAN",
    image: "BharniBigDhakkan.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
  {
    name: "Small Bharni Dhakkan",
    hindiName: "छोटी भरनी का ढक्कन",
    requirementType: "BARTAN",
    image: "SmallBharniDhakkan.avif",
    bagSize: 1,
    quantity: 100000000000000,
    unit: "piece",
    minimumStock: 50,
  },
];

export default bartanInventory;