const furnitureInventory = [
    {
  name: "Office Table",
  hindiName: "ऑफिस टेबल",
  requirementType: "FURNITURE",
  image: "OfficeTable.avif",
  bagSize: 1,
  quantity: 100000000000000,
  unit: "piece",
  minimumStock: 50,
},
{
  name: "Book Case",
  hindiName: "बुक केस",
  requirementType: "FURNITURE",
  image: "BookCase.avif",
  bagSize: 1,
  quantity: 100000000000000,
  unit: "piece",
  minimumStock: 50,
},
{
  name: "Almirah",
  hindiName: "अलमारी",
  requirementType: "FURNITURE",
  image: "Almirah.avif",
  bagSize: 1,
  quantity: 100000000000000,
  unit: "piece",
  minimumStock: 50,
},
{
  name: "Plastic Chair",
  hindiName: "प्लास्टिक कुर्सी",
  requirementType: "FURNITURE",
  image: "PlasticChair.avif",
  bagSize: 1,
  quantity: 100000000000000,
  unit: "piece",
  minimumStock: 50,
},
{
  name: "Moving Chair",
  hindiName: "मूविंग चेयर",
  requirementType: "FURNITURE",
  image: "MovingChair.avif",
  bagSize: 1,
  quantity: 100000000000000,
  unit: "piece",
  minimumStock: 50,
},
{
  name: "Rack",
  hindiName: "रैक",
  requirementType: "FURNITURE",
  image: "Rack.avif",
  bagSize: 1,
  quantity: 100000000000000,
  unit: "piece",
  minimumStock: 50,
},

]

export default furnitureInventory