// export const STATUS = {

//     DRAFT:"DRAFT",

//     SUBMITTED:"SUBMITTED",

//     APPROVED:"APPROVED",

//     PARTIALLY_APPROVED:"PARTIALLY_APPROVED",

//     PACKING:"PACKING",

//     PACKED:"PACKED",

//     OUT_FOR_DELIVERY:"OUT_FOR_DELIVERY",

//     DELIVERED:"DELIVERED",

//     RECEIVED_PENDING_CONFIRMATION:"RECEIVED_PENDING_CONFIRMATION",

//     RECEIVED:"RECEIVED",

//     REJECTED:"REJECTED",

//     CANCELLED:"CANCELLED"

// }

