export const NOTIFICATION_TYPE = {
  REQUIREMENT_CREATED: "REQUIREMENT_CREATED",
  REQUIREMENT_DISPATCHED: "REQUIREMENT_DISPATCHED",
  REQUIREMENT_RECEIVED: "REQUIREMENT_RECEIVED",
  LOW_STOCK: "LOW_STOCK",
};